import { Schema, model } from "mongoose";
const PostSchema = new Schema(
  {
    name: { type: String, required: false, default: "post" },
    title_P: { type: String, required: false, default: null },
    color_title_P: { type: String, required: false, default: null },
    subTitle_P: { type: String, required: false, default: null },
    color_subTitle_P: { type: String, required: false, default: null },
    title_1: { type: String, required: false, default: null },
    color_title_1: { type: String, required: false, default: null },
    subTitle_1: { type: String, required: false, default: null },
    color_subTitle_1: { type: String, required: false, default: null },
    title_2: { type: String, required: false, default: null },
    color_title_2: { type: String, required: false, default: null },
    subTitle_2: { type: String, required: false, default: null },
    color_subTitle_2: { type: String, required: false, default: null },
    title_3: { type: String, required: false, default: null },
    color_title_3: { type: String, required: false, default: null },
    subTitle_3: { type: String, required: false, default: null },
    color_subTitle_3: { type: String, required: false, default: null },
    title_4: { type: String, required: false, default: null },
    color_title_4: { type: String, required: false, default: null },
    subTitle_4: { type: String, required: false, default: null },
    color_subTitle_4: { type: String, required: false, default: null },
    title_5: { type: String, required: false, default: null },
    color_title_5: { type: String, required: false, default: null },
    subTitle_5: { type: String, required: false, default: null },
    color_subTitle_5: { type: String, required: false, default: null },
    title_6: { type: String, required: false, default: null },
    color_title_6: { type: String, required: false, default: null },
    subTitle_6: { type: String, required: false, default: null },
    color_subTitle_6: { type: String, required: false, default: null },
    title_7: { type: String, required: false, default: null },
    color_title_7: { type: String, required: false, default: null },
    subTitle_7: { type: String, required: false, default: null },
    color_subTitle_7: { type: String, required: false, default: null },
    link_1: { type: String, required: false, default: null },
    txt_link_1: { type: String, required: false, default: null },
    link_2: { type: String, required: false, default: null },
    txt_link_2: { type: String, required: false, default: null },
    link_3: { type: String, required: false, default: null },
    txt_link_3: { type: String, required: false, default: null },
    link_4: { type: String, required: false, default: null },
    txt_link_4: { type: String, required: false, default: null },
    link_5: { type: String, required: false, default: null },
    txt_link_5: { type: String, required: false, default: null },
    link_6: { type: String, required: false, default: null },
    txt_link_6: { type: String, required: false, default: null },
    link_7: { type: String, required: false, default: null },
    txt_link_7: { type: String, required: false, default: null },
    p_1: { type: String, required: false, default: null },
    p_2: { type: String, required: false, default: null },
    p_3: { type: String, required: false, default: null },
    p_4: { type: String, required: false, default: null },
    p_5: { type: String, required: false, default: null },
    p_6: { type: String, required: false, default: null },
    p_7: { type: String, required: false, default: null },
    theme: { type: String, required: false, default: "actualite" },
    lang: { type: String, required: false, default: "fr" },
    imageUrl: { type: String, default: null },
    postOpened: { type: Number, default: 0 },
    postRead: { type: Number, default: 0 },

    postGeoloc: [{ type: String }],
    pN: { type: Boolean, default: true },
  },
  {
    timestamps: true,
  }
);

export default model("Post", PostSchema);